# Generated by Django 5.0.6 on 2025-02-11 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('expenses', 'expenses'), ('income', 'income')], max_length=30, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, choices=[('housing', 'Housing'), ('utilities', 'Utilities'), ('food', 'Food & Groceries'), ('transportation', 'Transportation'), ('health', 'Health & Medical'), ('entertainment', 'Entertainment'), ('fitness', 'Fitness & Sports'), ('shopping', 'Shopping'), ('personal_care', 'Personal Care'), ('subscriptions', 'Subscriptions & Memberships'), ('debt', 'Debt Repayments'), ('savings', 'Savings & Investments'), ('insurance', 'Insurance'), ('taxes', 'Taxes'), ('education', 'Education'), ('gifts', 'Gifts & Donations'), ('childcare', 'Childcare'), ('travel', 'Travel'), ('emergency', 'Emergency Expenses'), ('misc', 'Miscellaneous')], max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
